name: Source Code Formatting, Building Status & Linting

on:
  pull_request:
    branches: ["dev", "master"]
  #push:
  #  branches: ["master"]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Packages
        run: npm ci
      -
        name: Application Build Status
        run: npm run build
      -
        name: Code Formatting
        run: npx prettier --write ./src
      -
        name: Auto Commit Code Formatting
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Commit Code Formatting
          branch: ${{ github.head_ref }}
      -
        name: Code Linting
        run: npx eslint ./src
